export const language = {
    pl : {
        appName: 'Nauka Liczenia',
        menuSettings: 'Ustawienia',
        menuQuestNo: 'Liczba pytań',
        menuOperation: 'Działanie',
        menuMultiplication: 'Mnożenie',
        menuAddition: 'Dodawanie',
        menuSubtraction: 'Odejmowanie',
        menuDivision: 'Dzielenie',
        menuRange: 'Zakres działania',
        menuRangeMin: 'od',
        menuRangeMax: 'do',
        menuErrMsgPositive: 'Parametry muszą być większe od zera!',
        menuErrMsgIncrease: 'Pole "od" musi być mniejsze od pola "do"',
        menuSubject: 'Wybierz temat',
        menuNumbers: 'Liczby',
        menuColors: 'Kolory',
        menuAnimals: 'Zwierzęta',
        menuPositions: 'Położenie',
        menuWeekdays: 'Dni tygodnia itp.',
        testQuestNo: 'Pytanie nr ',
        testNext: 'Następne pytanie',
        summaryYourResult: 'Twój wynik to',
        summaryYourAns: 'Twoje odpowiedzi',
        summarySholdBe: ' powinno być ',
        summaryMaster: 'Mistrzunio!',
        summaryCouldBeBett: 'Mogło być lepiej',
        summaryNotBad: 'Nieźle :)',
        summaryPoor: 'Cienizna :(',
        summaryNewTest: 'Rozpocznij nowy test',
        chooseLesson: 'Wybierz lekcję',
        chooseCalcLesson: 'Lekcja liczenia',
        chooseEnLesson: 'Lekcja angielskiego',
    },
    cz : {
        appName: 'Nauč se Počítat',
        menuSettings: 'Nastavení',
        menuQuestNo: 'Počet otázek',
        menuOperation: 'Operace',
        menuMultiplication: 'Násobení',
        menuAddition: 'Sčítání',
        menuSubtraction: 'Odčítání',
        menuDivision: 'Dělení',
        menuRange: 'Rozsah operace',
        menuRangeMin: 'od',
        menuRangeMax: 'do',
        menuErrMsgPositive: 'Hodnoty musí být větší než nula!',
        menuErrMsgIncrease: 'Pole „od“ musí být menší než pole „do“.',
        menuSubject: 'Vybrat téma',
        menuNumbers: 'Čísla',
        menuColors: 'Barvy',
        menuAnimals: 'Zvířata',
        menuPositions: 'Pozice',
        menuWeekdays: 'Dny v týdnu atd.',
        testQuestNo: 'Otázka č. ',
        testNext: 'Další otázka',
        summaryYourResult: 'Tvůj výsledek',
        summaryYourAns: 'Tvoje odpovědi',
        summarySholdBe: ' by měl ',
        summaryMaster: 'Mistr!',
        summaryCouldBeBett: 'Mohlo by být lépe',
        summaryNotBad: 'Není to špatné',
        summaryPoor: 'Špatně :(',
        summaryNewTest: 'Spustit nový test',
        chooseLesson: 'Vyber lekci',
        chooseCalcLesson: 'Lekce matematiky',
        chooseEnLesson: 'Lekce angličtiny',
    }
}